<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cloudml" nsURI="http://cloudml.net" nsPrefix="net.cloudml">
  <eSubpackages name="core" nsURI="http://cloudml.net/core" nsPrefix="net.cloudml.core">
    <eClassifiers xsi:type="ecore:EClass" name="CloudMLElement" abstract="true" interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//core/CloudMLElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WithProperties" abstract="true" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
          eType="#//core/Property" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//core/WithProperties">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="retrievingCommand" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="deployingCommand" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="configurationCommand"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startCommand" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopCommand" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="uploadCommand" upperBound="-1"
          eType="#//core/UploadCommand" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Provider" eSuperTypes="#//core/WithProperties">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="credentials" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeploymentModel" eSuperTypes="#//core/WithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="providers" upperBound="-1"
          eType="#//core/Provider" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="artefactTypes" upperBound="-1"
          eType="#//core/Artefact" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nodeTypes" upperBound="-1"
          eType="#//core/Node" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindingTypes" upperBound="-1"
          eType="#//core/Binding" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="artefactInstances" upperBound="-1"
          eType="#//core/ArtefactInstance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nodeInstances" upperBound="-1"
          eType="#//core/NodeInstance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindingInstances" upperBound="-1"
          eType="#//core/BindingInstance" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactPort" abstract="true" eSuperTypes="#//core/WithProperties">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="portNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRemote" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ServerPort" eSuperTypes="#//core/ArtefactPort"/>
    <eClassifiers xsi:type="ecore:EClass" name="ClientPort" eSuperTypes="#//core/ArtefactPort">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOptional" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Artefact" eSuperTypes="#//core/WithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="destination" eType="#//core/ArtefactPort"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="#//core/Resource"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="provided" upperBound="-1"
          eType="#//core/ServerPort" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="required" upperBound="-1"
          eType="#//core/ClientPort" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//core/WithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="cloudProvider" lowerBound="1"
          eType="#//core/Provider"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minRam" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minCore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minDisk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OS" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sshKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="securityGroup" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="privateKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="is64os" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactPortInstance" eSuperTypes="#//core/WithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/ArtefactPort"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ServerPortInstance" eSuperTypes="#//core/ArtefactPortInstance"/>
    <eClassifiers xsi:type="ecore:EClass" name="ClientPortInstance" eSuperTypes="#//core/ArtefactPortInstance"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtefactInstance" eSuperTypes="#//core/WithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/Artefact"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="destination" eType="#//core/NodeInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="provided" upperBound="-1"
          eType="#//core/ServerPortInstance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="required" upperBound="-1"
          eType="#//core/ClientPortInstance" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NodeInstance" eSuperTypes="#//core/WithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/Node"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Composite" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="containedArtefacts" upperBound="-1"
          eType="#//core/ArtefactInstance" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Binding" eSuperTypes="#//core/WithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="client" eType="#//core/ClientPort"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="server" eType="#//core/ServerPort"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="clientResource" eType="#//core/Resource"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="serverResource" eType="#//core/Resource"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BindingInstance" eSuperTypes="#//core/WithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/Binding"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="client" eType="#//core/ClientPortInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="server" eType="#//core/ServerPortInstance"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UploadCommand">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
