<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cloudml" nsURI="http://cloudml.net" nsPrefix="net.cloudml">
  <eSubpackages name="core" nsURI="http://cloudml.net/core" nsPrefix="net.cloudml.core">
    <eClassifiers xsi:type="ecore:EClass" name="CloudMLElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//core/CloudMLElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CloudMLElementWithProperties" abstract="true"
        eSuperTypes="#//core/CloudMLElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
          eType="#//core/Property" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
          eType="#//core/Resource" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="puppetResources" upperBound="-1"
          eType="#//core/PuppetResource" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dockerResources" upperBound="-1"
          eType="#//core/DockerResource"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//core/CloudMLElementWithProperties">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="downloadCommand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uploadCommand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="installCommand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="configureCommand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startCommand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopCommand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="requireCredentials" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="executeLocally" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CloudMLModel" eSuperTypes="#//core/CloudMLElementWithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="providers" upperBound="-1"
          eType="#//core/Provider" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
          eType="#//core/Component" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="clouds" upperBound="-1"
          eType="#//core/Cloud" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentInstances" upperBound="-1"
          eType="#//core/ComponentInstance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="internalComponents" upperBound="-1"
          eType="#//core/InternalComponent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="externalComponents" upperBound="-1"
          eType="#//core/ExternalComponent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="internalComponentInstances"
          upperBound="-1" eType="#//core/InternalComponentInstance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="externalComponentInstances"
          upperBound="-1" eType="#//core/ExternalComponentInstance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="vms" upperBound="-1"
          eType="#//core/VM" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="vmInstances" upperBound="-1"
          eType="#//core/VMInstance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" upperBound="-1"
          eType="#//core/Relationship" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relationshipInstances"
          upperBound="-1" eType="#//core/RelationshipInstance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="executesInstances" upperBound="-1"
          eType="#//core/ExecuteInstance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resourcePools" upperBound="-1"
          eType="#//core/ResourcesPool" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VM" eSuperTypes="#//core/ExternalComponent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="provided" upperBound="-1"
          eType="#//core/VMPort" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minRam" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxRam" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minCores" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxCores" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minStorage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxStorage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="os" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="is64os" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="securityGroup" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sshKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="privateKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="providerSpecificTypeName"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VMPort" eSuperTypes="#//core/CloudMLElementWithProperties"/>
    <eClassifiers xsi:type="ecore:EClass" name="Provider" eSuperTypes="#//core/CloudMLElementWithProperties">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="credentials" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="login" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true" eSuperTypes="#//core/CloudMLElementWithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedPorts" upperBound="-1"
          eType="#//core/ProvidedPort" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedExecutionPlatforms"
          upperBound="-1" eType="#//core/ProvidedExecutionPlatform" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InternalComponent" eSuperTypes="#//core/Component">
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredPorts" upperBound="-1"
          eType="#//core/RequiredPort" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="compositeInternalComponents"
          upperBound="-1" eType="#//core/InternalComponent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredExecutionPlatform"
          lowerBound="1" eType="#//core/RequiredExecutionPlatform" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true" eSuperTypes="#//core/CloudMLElementWithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
          eType="#//core/Component"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLocal" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="portNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RequiredPort" eSuperTypes="#//core/Port">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMandatory" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProvidedPort" eSuperTypes="#//core/Port"/>
    <eClassifiers xsi:type="ecore:EClass" name="Relationship" eSuperTypes="#//core/CloudMLElementWithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredPort" lowerBound="1"
          eType="#//core/RequiredPort"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedPort" lowerBound="1"
          eType="#//core/ProvidedPort"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredPortResource"
          eType="#//core/Resource" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedPortResource"
          eType="#//core/Resource" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Cloud" eSuperTypes="#//core/CloudMLElementWithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="vmInstances" upperBound="-1"
          eType="#//core/VMInstance" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VMInstance" eSuperTypes="#//core/ExternalComponentInstance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="provided" upperBound="-1"
          eType="#//core/VMPortInstance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VMPortInstance" eSuperTypes="#//core/CloudMLElementWithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/VMPort"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentInstance" abstract="true"
        eSuperTypes="#//core/CloudMLElementWithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedPortInstances"
          upperBound="-1" eType="#//core/ProvidedPortInstance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/Component"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedExecutionPlatformInstances"
          upperBound="-1" eType="#//core/ProvidedExecutionPlatformInstance" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InternalComponentInstance" eSuperTypes="#//core/ComponentInstance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredPortInstances"
          upperBound="-1" eType="#//core/RequiredPortInstance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredExecutionPlatformInstance"
          lowerBound="1" eType="#//core/RequiredExecutionPlatformInstance" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PortInstance" eSuperTypes="#//core/CloudMLElementWithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/Port"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentInstance" lowerBound="1"
          eType="#//core/ComponentInstance"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RequiredPortInstance" eSuperTypes="#//core/PortInstance"/>
    <eClassifiers xsi:type="ecore:EClass" name="ProvidedPortInstance" eSuperTypes="#//core/PortInstance"/>
    <eClassifiers xsi:type="ecore:EClass" name="RelationshipInstance" eSuperTypes="#//core/CloudMLElementWithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/Relationship"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredPortInstance"
          lowerBound="1" eType="#//core/RequiredPortInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedPortInstance"
          lowerBound="1" eType="#//core/ProvidedPortInstance"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalComponent" eSuperTypes="#//core/Component">
      <eStructuralFeatures xsi:type="ecore:EReference" name="provider" eType="#//core/Provider"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="endPoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="provide" upperBound="-1"
          eType="#//core/VMPort" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="login" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="passwd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Region" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalComponentInstance" eSuperTypes="#//core/ComponentInstance">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ips" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="provide" upperBound="-1"
          eType="#//core/VMPortInstance" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExecutionPlatform" abstract="true"
        eSuperTypes="#//core/CloudMLElementWithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1"
          eType="#//core/Component"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExecutionPlatformInstance" abstract="true"
        eSuperTypes="#//core/CloudMLElementWithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1"
          eType="#//core/ComponentInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/ExecutionPlatform"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProvidedExecutionPlatform" eSuperTypes="#//core/ExecutionPlatform">
      <eStructuralFeatures xsi:type="ecore:EReference" name="offers" upperBound="-1"
          eType="#//core/Property" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProvidedExecutionPlatformInstance"
        eSuperTypes="#//core/ExecutionPlatformInstance"/>
    <eClassifiers xsi:type="ecore:EClass" name="RequiredExecutionPlatform" eSuperTypes="#//core/ExecutionPlatform">
      <eStructuralFeatures xsi:type="ecore:EReference" name="demands" upperBound="-1"
          eType="#//core/Property" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RequiredExecutionPlatformInstance"
        eSuperTypes="#//core/ExecutionPlatformInstance"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExecuteInstance" eSuperTypes="#//core/CloudMLElementWithProperties">
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedExecutionPlatformInstance"
          lowerBound="1" eType="#//core/ProvidedExecutionPlatformInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredExecutionPlatformInstance"
          lowerBound="1" eType="#//core/RequiredExecutionPlatformInstance"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PuppetResource" eSuperTypes="#//core/Resource">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="masterEndpoint" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="repositoryEndpoint" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="configureHostnameCommand"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="repositoryKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="configurationFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="manifestEntry" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourcesPool" eSuperTypes="#//core/CloudMLElementWithProperties">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minReplicats" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxReplicats" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbReplicats" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="baseInstances" lowerBound="1"
          upperBound="-1" eType="#//core/VMInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="replicats" upperBound="-1"
          eType="#//core/VMInstance"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DockerResource" eSuperTypes="#//core/Resource">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dockerFilePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
