<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="UML_Activity_mine" nsURI="http://www.example.org/UML_Activity_mine"
    nsPrefix="UML_Activity_mine">
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="properties" eType="#//HashMap"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" lowerBound="1" upperBound="-1"
        eType="#//ActivityNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" lowerBound="1" upperBound="-1"
        eType="#//ActivityEdge" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityEdge" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectFlow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ActivityNode" eOpposite="#//ActivityNode/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ActivityNode" eOpposite="#//ActivityNode/outgoing"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//ActivityEdge" eOpposite="#//ActivityEdge/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//ActivityEdge" eOpposite="#//ActivityEdge/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ArrayList" instanceClassName="java.util.ArrayList"/>
  <eClassifiers xsi:type="ecore:EDataType" name="HashMap" instanceClassName="java.util.HashMap"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="IN"/>
    <eLiterals name="OUT" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlNode" abstract="true" eSuperTypes="#//ActivityNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectNode" eSuperTypes="#//ActivityNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objects" lowerBound="1"
        eType="#//ArrayList"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//ActivityNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputs" eType="#//ArrayList"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputs" eType="#//ArrayList"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fork" eSuperTypes="#//ControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Join" eSuperTypes="#//ControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityInitialNode" eSuperTypes="#//ControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityFinalNode" eSuperTypes="#//ControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="DatastoreNode" eSuperTypes="#//ObjectNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityParameterNode" eSuperTypes="#//ObjectNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpansionNode" eSuperTypes="#//ObjectNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpansionRegion" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputCollections" lowerBound="1"
        upperBound="-1" eType="#//ExpansionNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputCollections" upperBound="-1"
        eType="#//ExpansionNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" lowerBound="1" upperBound="-1"
        eType="#//ActivityEdge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" lowerBound="1" upperBound="-1"
        eType="#//ActivityNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ExpansionMode">
    <eLiterals name="PARALLEL"/>
    <eLiterals name="ITERATIVE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Status">
    <eLiterals name="INACTIVE"/>
    <eLiterals name="ACTIVE"/>
    <eLiterals name="DONE"/>
  </eClassifiers>
</ecore:EPackage>
