
package net.flexiant.extility;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for errorInvalidInput.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="errorInvalidInput">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="REQUIRED_FIELD_NOT_SET"/>
 *     &lt;enumeration value="INVALID_DATE_FORMAT"/>
 *     &lt;enumeration value="INVALID_DATE_RANGE"/>
 *     &lt;enumeration value="INVALID_REFERRAL_PRIORITY"/>
 *     &lt;enumeration value="INVALID_REFERRAL_SCHEME_NAME"/>
 *     &lt;enumeration value="NO_REFERRAL_PROMOTION_UUID_DEFINED"/>
 *     &lt;enumeration value="INVALID_REFERRAL_EMAIL_SUBJECT"/>
 *     &lt;enumeration value="INVALID_REFERRAL_EMAIL_BODY"/>
 *     &lt;enumeration value="INVALID_REFERRAL_INVITEE_UNITS"/>
 *     &lt;enumeration value="INVALID_REFERRAL_INVITOR_UNITS"/>
 *     &lt;enumeration value="INVALID_INVITEE_MINIMUM_PURCHASE"/>
 *     &lt;enumeration value="INVALID_REFERRAL_UNIT_COST"/>
 *     &lt;enumeration value="INVALID_MAX_OUTSTANDING"/>
 *     &lt;enumeration value="INVALID_CURRENT_OUTSTANDING"/>
 *     &lt;enumeration value="INVALID_EXPIRY_DAYS"/>
 *     &lt;enumeration value="NO_REFERRAL_SCHEME_DEFINED"/>
 *     &lt;enumeration value="NO_REFERRAL_PROMO_CODE_DEFINED"/>
 *     &lt;enumeration value="INVALID_INVITOR_CUSTOMER_ID"/>
 *     &lt;enumeration value="INVALID_EMAIL_ADDRESS"/>
 *     &lt;enumeration value="INVALID_EXPIRY_DATE"/>
 *     &lt;enumeration value="INVALID_STATUS"/>
 *     &lt;enumeration value="NO_PRODUCT_OFFER_DEFINED"/>
 *     &lt;enumeration value="INVALID_PRODUCT_OFFER"/>
 *     &lt;enumeration value="INVALID_BILLING_PERIOD"/>
 *     &lt;enumeration value="NO_PRODUCT_ID_DEFINED"/>
 *     &lt;enumeration value="PROMOTION_IS_EXPIRED"/>
 *     &lt;enumeration value="PROMOTION_NAME_ALREADY_EXISTS"/>
 *     &lt;enumeration value="INVALID_PROMO_CODE"/>
 *     &lt;enumeration value="NO_PROMOTION_DEFINED"/>
 *     &lt;enumeration value="NO_PROMOTION_CODE_DEFINED"/>
 *     &lt;enumeration value="NO_PROMOTION_FILTER_DEFINED"/>
 *     &lt;enumeration value="NO_PROMOTION_NAME_DEFINED"/>
 *     &lt;enumeration value="CANNOT_ASSOCIATE_CUSTOMER_TO_PROMOTION"/>
 *     &lt;enumeration value="INVALID_PROMO_TYPE_ID"/>
 *     &lt;enumeration value="NO_PROMO_CODE_DEFINED"/>
 *     &lt;enumeration value="PROMOTION_CODE_NAME_ALREADY_EXISTS"/>
 *     &lt;enumeration value="NO_PROMOTION_UUID_DEFINED"/>
 *     &lt;enumeration value="NO_BILLING_ENTITY_DEFINED"/>
 *     &lt;enumeration value="NO_BILLING_ENTITY_NAME_DEFINED"/>
 *     &lt;enumeration value="INVALID_BILLING_ENTITY"/>
 *     &lt;enumeration value="INVALID_CURRENCY_ID"/>
 *     &lt;enumeration value="NO_USER_DEFINED"/>
 *     &lt;enumeration value="NO_PASSWORD_DEFINED"/>
 *     &lt;enumeration value="NO_CUSTOMER_UUID_DEFINED"/>
 *     &lt;enumeration value="NO_CUSTOMER_ID_DEFINED"/>
 *     &lt;enumeration value="NO_ORGANISATION_NAME_DEFINED"/>
 *     &lt;enumeration value="NO_ADDRESS_DEFINED"/>
 *     &lt;enumeration value="NO_CUSTOMER_DEFINED"/>
 *     &lt;enumeration value="NO_DESCRIPTION_DEFINED"/>
 *     &lt;enumeration value="NO_CURRENCYID_DEFINED"/>
 *     &lt;enumeration value="NO_USERID_DEFINED"/>
 *     &lt;enumeration value="NO_3DS_28_DAY_SPEND_LIMIT_DEFINED"/>
 *     &lt;enumeration value="NO_OVERALL_28_DAY_SPEND_LIMIT_DEFINED"/>
 *     &lt;enumeration value="NO_LIMITS_DEFINED"/>
 *     &lt;enumeration value="NO_VDC_DEFINED"/>
 *     &lt;enumeration value="NO_CREDIT_LIMIT_DEFINED"/>
 *     &lt;enumeration value="NO_EMAIL_TEMPLATE_DEFINED"/>
 *     &lt;enumeration value="NO_EMAIL_TYPE_DEFINED"/>
 *     &lt;enumeration value="NO_USER_UUID_DEFINED"/>
 *     &lt;enumeration value="INVALID_GROUP"/>
 *     &lt;enumeration value="INVALID_GROUP_TYPE"/>
 *     &lt;enumeration value="NO_TRANSACTION_TYPE_DEFINED"/>
 *     &lt;enumeration value="NO_UNITS_DEFINED"/>
 *     &lt;enumeration value="NO_UNIT_TYPE_DEFINED"/>
 *     &lt;enumeration value="NO_TRANSACTION_AMOUNT_DEFINED"/>
 *     &lt;enumeration value="NO_INVOICE_NO_DEFINED"/>
 *     &lt;enumeration value="INVALID_RESOURCE_UUID"/>
 *     &lt;enumeration value="RESOURCE_KEY_CANNOT_BE_NULL"/>
 *     &lt;enumeration value="INVALID_RESOURCE_METADATA"/>
 *     &lt;enumeration value="INVALID_RESOURCE_KEY_TYPE"/>
 *     &lt;enumeration value="INVALID_SERVER_UUID"/>
 *     &lt;enumeration value="NIC_CANNOT_BE_NULL"/>
 *     &lt;enumeration value="DISK_CANNOT_BE_NULL"/>
 *     &lt;enumeration value="INVALID_DISK_UUID"/>
 *     &lt;enumeration value="INVALID_IMAGE_UUID"/>
 *     &lt;enumeration value="NO_DISK_NAME_SPECIFIED"/>
 *     &lt;enumeration value="VDC_CANNOT_BE_NULL"/>
 *     &lt;enumeration value="INVALID_START_DATE"/>
 *     &lt;enumeration value="INVALID_PRIVATE_METADATA"/>
 *     &lt;enumeration value="INVALID_PUBLIC_METADATA"/>
 *     &lt;enumeration value="INVALID_RESTRICTED_METADATA"/>
 *     &lt;enumeration value="INVALID_NIC_UUID"/>
 *     &lt;enumeration value="INVALID_VDC_UUID"/>
 *     &lt;enumeration value="INVALID_BASE_TYPE"/>
 *     &lt;enumeration value="SERVER_CANNOT_BE_NULL"/>
 *     &lt;enumeration value="INVALID_SERVER_NAME"/>
 *     &lt;enumeration value="NETWORK_CANNOT_BE_NULL"/>
 *     &lt;enumeration value="INVALID_NETWORK_TYPE"/>
 *     &lt;enumeration value="INVALID_JOB_UUID"/>
 *     &lt;enumeration value="NO_RESOURCE_TYPE_DEFINED"/>
 *     &lt;enumeration value="INVALID_SSHKEY_UUID"/>
 *     &lt;enumeration value="INVALID_INDEX"/>
 *     &lt;enumeration value="RESOURCE_CANNOT_BE_NULL"/>
 *     &lt;enumeration value="NO_RESOURCE_KEY_DEFINED"/>
 *     &lt;enumeration value="NO_FETCH_PARAMETERS_DEFINED"/>
 *     &lt;enumeration value="RESOURCE_NAME_CANNOT_BE_NULL"/>
 *     &lt;enumeration value="NO_RESOURCE_NAME_DEFINED"/>
 *     &lt;enumeration value="SSHKEY_CANNOT_BE_NULL"/>
 *     &lt;enumeration value="INVALID_FIREWALL_PROTOCOL"/>
 *     &lt;enumeration value="INVALID_FIREWALL_DIRECTION"/>
 *     &lt;enumeration value="INVALID_FIREWALL_ACTION"/>
 *     &lt;enumeration value="INVALID_FIREWALL_CONN_STATE"/>
 *     &lt;enumeration value="INVALID_SUBNET_TYPE"/>
 *     &lt;enumeration value="INVALID_USER_NAME_FORMAT"/>
 *     &lt;enumeration value="INVALID_PASSWORD_FORMAT"/>
 *     &lt;enumeration value="INVALID_CHECKSUM_FORMAT"/>
 *     &lt;enumeration value="NO_JOB_FOUND"/>
 *     &lt;enumeration value="INVALID_IP_ADDRESS"/>
 *     &lt;enumeration value="INVALID_NETMASK"/>
 *     &lt;enumeration value="INVALID_IP_TYPE"/>
 *     &lt;enumeration value="SNAPSHOT_CANNOT_BE_NULL"/>
 *     &lt;enumeration value="NO_SNAPSHOT_TYPE_DEFINED"/>
 *     &lt;enumeration value="NO_SNAPSHOT_PARENT_UUID_DEFINED"/>
 *     &lt;enumeration value="NO_SNAPSHOT_NAME_DEFINED"/>
 *     &lt;enumeration value="INVALID_NETWORK_UUID"/>
 *     &lt;enumeration value="INVALID_SUBNET_UUID"/>
 *     &lt;enumeration value="NO_BASE_UUID_SET"/>
 *     &lt;enumeration value="CAPABILITIES_SET_CANNOT_BE_NULL"/>
 *     &lt;enumeration value="INVALID_FILTER_FIELD"/>
 *     &lt;enumeration value="INVALID_SERVER_STATE"/>
 *     &lt;enumeration value="INVALID_CAPABILITY"/>
 *     &lt;enumeration value="INVALID_RESOURCE_TYPE"/>
 *     &lt;enumeration value="ENUM_CANNOT_BE_NULL"/>
 *     &lt;enumeration value="ENUM_DO_NOT_IMPLEMENT_DBENUM"/>
 *     &lt;enumeration value="NO_VDC_UUID_DEFINED"/>
 *     &lt;enumeration value="NO_CLUSTER_DEFINED"/>
 *     &lt;enumeration value="NO_CLUSTER_NAME_DEFINED"/>
 *     &lt;enumeration value="RESOURCE_IS_NOT_VIRTUAL_RESOURCE"/>
 *     &lt;enumeration value="INVALID_CLUSTER_UUID"/>
 *     &lt;enumeration value="INVALID_INPUT"/>
 *     &lt;enumeration value="INVALID_USER_UUID"/>
 *     &lt;enumeration value="GROUP_CANNOT_BE_NULL"/>
 *     &lt;enumeration value="NO_PAYMENT_CARD_DEFINED"/>
 *     &lt;enumeration value="INVALID_PAYMENT_METHOD_ID"/>
 *     &lt;enumeration value="CLUSTER_CANNOT_BE_NULL"/>
 *     &lt;enumeration value="STORAGE_UNIT_CANNOT_BE_NULL"/>
 *     &lt;enumeration value="NO_PRODUCT_DEFINED"/>
 *     &lt;enumeration value="PRODUCT_ID_FOR_DIFFERENT_PRODUCT"/>
 *     &lt;enumeration value="NO_PAYMENT_METHOD_DEFINED"/>
 *     &lt;enumeration value="NO_PAYMENT_PROVIDER_DEFINED"/>
 *     &lt;enumeration value="NO_PAYMENT_METHOD_NAME_DEFINED"/>
 *     &lt;enumeration value="NO_PAYMENT_METHOD_UUID_DEFINED"/>
 *     &lt;enumeration value="INVALID_PAYMENT_METHOD_UUID"/>
 *     &lt;enumeration value="INVALID_PRODUCT_COMPONENTS"/>
 *     &lt;enumeration value="NO_INVOICE_DEFINED"/>
 *     &lt;enumeration value="INVALID_INVOICE_NUMBER"/>
 *     &lt;enumeration value="INVALID_INVOICE_SOURCE"/>
 *     &lt;enumeration value="INVALID_INVOICE_PAYMENT_PROVIDER"/>
 *     &lt;enumeration value="INVALID_INVOICE_PAYMENT_PROVIDER_REFERENCE"/>
 *     &lt;enumeration value="NO_PURCHASE_REFERENCE_DEFINED"/>
 *     &lt;enumeration value="NO_INVOICE_UUID_DEFINED"/>
 *     &lt;enumeration value="NO_TRANSACTION_LOG_DEFINED"/>
 *     &lt;enumeration value="NO_SERVER_SPECIFIED"/>
 *     &lt;enumeration value="NO_AGGREGATION_FUNCTION_DEFINED"/>
 *     &lt;enumeration value="NO_AGGREGATION_FIELD_DEFINED"/>
 *     &lt;enumeration value="INVALID_ORDER_BY_FIELD"/>
 *     &lt;enumeration value="INVALID_INVOICE_DATE"/>
 *     &lt;enumeration value="NO_OUTPUT_FIELDS_DEFINED"/>
 *     &lt;enumeration value="NO_START_OR_END_DATE_DEFINED"/>
 *     &lt;enumeration value="INVALID_AGGREGATION_CONDITION_IN_FILTER"/>
 *     &lt;enumeration value="NO_DEPLOYMENT_TEMPLATE_DEFINED"/>
 *     &lt;enumeration value="NO_DEPLOYMENT_TEMPLATE_UUID_DEFINED"/>
 *     &lt;enumeration value="INVALID_DEPLOYMENT_INSTANCE_UUID"/>
 *     &lt;enumeration value="NO_DEPLOYMENT_INSTANCE_DEFINED"/>
 *     &lt;enumeration value="NO_NETWORK_DEFINED"/>
 *     &lt;enumeration value="NO_CURRENCY_DEFINED"/>
 *     &lt;enumeration value="NO_CURRENCY_CODE_DEFINED"/>
 *     &lt;enumeration value="CURRENCY_CODE_LENGTH_CANNOT_BE_GREATER_THAN_3"/>
 *     &lt;enumeration value="EXISTING_CURRENCY_CODE"/>
 *     &lt;enumeration value="INVALID_NAMESPACE"/>
 *     &lt;enumeration value="NO_SUPPORT_FOR_MULTI_VALUES"/>
 *     &lt;enumeration value="INVALID_VALUE_SET_FOR_FIELD"/>
 *     &lt;enumeration value="INVALID_VALUE_INPUT"/>
 *     &lt;enumeration value="FDL_COMPILE_ERROR"/>
 *     &lt;enumeration value="FDL_REGISTER_ERROR"/>
 *     &lt;enumeration value="NO_SIZE_SPECIFIED"/>
 *     &lt;enumeration value="INVALID_URL"/>
 *     &lt;enumeration value="INVALID_PCT"/>
 *     &lt;enumeration value="PCT_NOT_DEFINED"/>
 *     &lt;enumeration value="INVALID_BILLING_METHOD"/>
 *     &lt;enumeration value="FDL_CODE_SIGNING_ERROR"/>
 *     &lt;enumeration value="NO_PRODUCT_COMPONENT_SPECIFIED"/>
 *     &lt;enumeration value="REQUIRED_PRODUCT_COMPONENTS_NOT_SET"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "errorInvalidInput")
@XmlEnum
public enum ErrorInvalidInput {

    REQUIRED_FIELD_NOT_SET("REQUIRED_FIELD_NOT_SET"),
    INVALID_DATE_FORMAT("INVALID_DATE_FORMAT"),
    INVALID_DATE_RANGE("INVALID_DATE_RANGE"),
    INVALID_REFERRAL_PRIORITY("INVALID_REFERRAL_PRIORITY"),
    INVALID_REFERRAL_SCHEME_NAME("INVALID_REFERRAL_SCHEME_NAME"),
    NO_REFERRAL_PROMOTION_UUID_DEFINED("NO_REFERRAL_PROMOTION_UUID_DEFINED"),
    INVALID_REFERRAL_EMAIL_SUBJECT("INVALID_REFERRAL_EMAIL_SUBJECT"),
    INVALID_REFERRAL_EMAIL_BODY("INVALID_REFERRAL_EMAIL_BODY"),
    INVALID_REFERRAL_INVITEE_UNITS("INVALID_REFERRAL_INVITEE_UNITS"),
    INVALID_REFERRAL_INVITOR_UNITS("INVALID_REFERRAL_INVITOR_UNITS"),
    INVALID_INVITEE_MINIMUM_PURCHASE("INVALID_INVITEE_MINIMUM_PURCHASE"),
    INVALID_REFERRAL_UNIT_COST("INVALID_REFERRAL_UNIT_COST"),
    INVALID_MAX_OUTSTANDING("INVALID_MAX_OUTSTANDING"),
    INVALID_CURRENT_OUTSTANDING("INVALID_CURRENT_OUTSTANDING"),
    INVALID_EXPIRY_DAYS("INVALID_EXPIRY_DAYS"),
    NO_REFERRAL_SCHEME_DEFINED("NO_REFERRAL_SCHEME_DEFINED"),
    NO_REFERRAL_PROMO_CODE_DEFINED("NO_REFERRAL_PROMO_CODE_DEFINED"),
    INVALID_INVITOR_CUSTOMER_ID("INVALID_INVITOR_CUSTOMER_ID"),
    INVALID_EMAIL_ADDRESS("INVALID_EMAIL_ADDRESS"),
    INVALID_EXPIRY_DATE("INVALID_EXPIRY_DATE"),
    INVALID_STATUS("INVALID_STATUS"),
    NO_PRODUCT_OFFER_DEFINED("NO_PRODUCT_OFFER_DEFINED"),
    INVALID_PRODUCT_OFFER("INVALID_PRODUCT_OFFER"),
    INVALID_BILLING_PERIOD("INVALID_BILLING_PERIOD"),
    NO_PRODUCT_ID_DEFINED("NO_PRODUCT_ID_DEFINED"),
    PROMOTION_IS_EXPIRED("PROMOTION_IS_EXPIRED"),
    PROMOTION_NAME_ALREADY_EXISTS("PROMOTION_NAME_ALREADY_EXISTS"),
    INVALID_PROMO_CODE("INVALID_PROMO_CODE"),
    NO_PROMOTION_DEFINED("NO_PROMOTION_DEFINED"),
    NO_PROMOTION_CODE_DEFINED("NO_PROMOTION_CODE_DEFINED"),
    NO_PROMOTION_FILTER_DEFINED("NO_PROMOTION_FILTER_DEFINED"),
    NO_PROMOTION_NAME_DEFINED("NO_PROMOTION_NAME_DEFINED"),
    CANNOT_ASSOCIATE_CUSTOMER_TO_PROMOTION("CANNOT_ASSOCIATE_CUSTOMER_TO_PROMOTION"),
    INVALID_PROMO_TYPE_ID("INVALID_PROMO_TYPE_ID"),
    NO_PROMO_CODE_DEFINED("NO_PROMO_CODE_DEFINED"),
    PROMOTION_CODE_NAME_ALREADY_EXISTS("PROMOTION_CODE_NAME_ALREADY_EXISTS"),
    NO_PROMOTION_UUID_DEFINED("NO_PROMOTION_UUID_DEFINED"),
    NO_BILLING_ENTITY_DEFINED("NO_BILLING_ENTITY_DEFINED"),
    NO_BILLING_ENTITY_NAME_DEFINED("NO_BILLING_ENTITY_NAME_DEFINED"),
    INVALID_BILLING_ENTITY("INVALID_BILLING_ENTITY"),
    INVALID_CURRENCY_ID("INVALID_CURRENCY_ID"),
    NO_USER_DEFINED("NO_USER_DEFINED"),
    NO_PASSWORD_DEFINED("NO_PASSWORD_DEFINED"),
    NO_CUSTOMER_UUID_DEFINED("NO_CUSTOMER_UUID_DEFINED"),
    NO_CUSTOMER_ID_DEFINED("NO_CUSTOMER_ID_DEFINED"),
    NO_ORGANISATION_NAME_DEFINED("NO_ORGANISATION_NAME_DEFINED"),
    NO_ADDRESS_DEFINED("NO_ADDRESS_DEFINED"),
    NO_CUSTOMER_DEFINED("NO_CUSTOMER_DEFINED"),
    NO_DESCRIPTION_DEFINED("NO_DESCRIPTION_DEFINED"),
    NO_CURRENCYID_DEFINED("NO_CURRENCYID_DEFINED"),
    NO_USERID_DEFINED("NO_USERID_DEFINED"),
    @XmlEnumValue("NO_3DS_28_DAY_SPEND_LIMIT_DEFINED")
    NO_3_DS_28_DAY_SPEND_LIMIT_DEFINED("NO_3DS_28_DAY_SPEND_LIMIT_DEFINED"),
    NO_OVERALL_28_DAY_SPEND_LIMIT_DEFINED("NO_OVERALL_28_DAY_SPEND_LIMIT_DEFINED"),
    NO_LIMITS_DEFINED("NO_LIMITS_DEFINED"),
    NO_VDC_DEFINED("NO_VDC_DEFINED"),
    NO_CREDIT_LIMIT_DEFINED("NO_CREDIT_LIMIT_DEFINED"),
    NO_EMAIL_TEMPLATE_DEFINED("NO_EMAIL_TEMPLATE_DEFINED"),
    NO_EMAIL_TYPE_DEFINED("NO_EMAIL_TYPE_DEFINED"),
    NO_USER_UUID_DEFINED("NO_USER_UUID_DEFINED"),
    INVALID_GROUP("INVALID_GROUP"),
    INVALID_GROUP_TYPE("INVALID_GROUP_TYPE"),
    NO_TRANSACTION_TYPE_DEFINED("NO_TRANSACTION_TYPE_DEFINED"),
    NO_UNITS_DEFINED("NO_UNITS_DEFINED"),
    NO_UNIT_TYPE_DEFINED("NO_UNIT_TYPE_DEFINED"),
    NO_TRANSACTION_AMOUNT_DEFINED("NO_TRANSACTION_AMOUNT_DEFINED"),
    NO_INVOICE_NO_DEFINED("NO_INVOICE_NO_DEFINED"),
    INVALID_RESOURCE_UUID("INVALID_RESOURCE_UUID"),
    RESOURCE_KEY_CANNOT_BE_NULL("RESOURCE_KEY_CANNOT_BE_NULL"),
    INVALID_RESOURCE_METADATA("INVALID_RESOURCE_METADATA"),
    INVALID_RESOURCE_KEY_TYPE("INVALID_RESOURCE_KEY_TYPE"),
    INVALID_SERVER_UUID("INVALID_SERVER_UUID"),
    NIC_CANNOT_BE_NULL("NIC_CANNOT_BE_NULL"),
    DISK_CANNOT_BE_NULL("DISK_CANNOT_BE_NULL"),
    INVALID_DISK_UUID("INVALID_DISK_UUID"),
    INVALID_IMAGE_UUID("INVALID_IMAGE_UUID"),
    NO_DISK_NAME_SPECIFIED("NO_DISK_NAME_SPECIFIED"),
    VDC_CANNOT_BE_NULL("VDC_CANNOT_BE_NULL"),
    INVALID_START_DATE("INVALID_START_DATE"),
    INVALID_PRIVATE_METADATA("INVALID_PRIVATE_METADATA"),
    INVALID_PUBLIC_METADATA("INVALID_PUBLIC_METADATA"),
    INVALID_RESTRICTED_METADATA("INVALID_RESTRICTED_METADATA"),
    INVALID_NIC_UUID("INVALID_NIC_UUID"),
    INVALID_VDC_UUID("INVALID_VDC_UUID"),
    INVALID_BASE_TYPE("INVALID_BASE_TYPE"),
    SERVER_CANNOT_BE_NULL("SERVER_CANNOT_BE_NULL"),
    INVALID_SERVER_NAME("INVALID_SERVER_NAME"),
    NETWORK_CANNOT_BE_NULL("NETWORK_CANNOT_BE_NULL"),
    INVALID_NETWORK_TYPE("INVALID_NETWORK_TYPE"),
    INVALID_JOB_UUID("INVALID_JOB_UUID"),
    NO_RESOURCE_TYPE_DEFINED("NO_RESOURCE_TYPE_DEFINED"),
    INVALID_SSHKEY_UUID("INVALID_SSHKEY_UUID"),
    INVALID_INDEX("INVALID_INDEX"),
    RESOURCE_CANNOT_BE_NULL("RESOURCE_CANNOT_BE_NULL"),
    NO_RESOURCE_KEY_DEFINED("NO_RESOURCE_KEY_DEFINED"),
    NO_FETCH_PARAMETERS_DEFINED("NO_FETCH_PARAMETERS_DEFINED"),
    RESOURCE_NAME_CANNOT_BE_NULL("RESOURCE_NAME_CANNOT_BE_NULL"),
    NO_RESOURCE_NAME_DEFINED("NO_RESOURCE_NAME_DEFINED"),
    SSHKEY_CANNOT_BE_NULL("SSHKEY_CANNOT_BE_NULL"),
    INVALID_FIREWALL_PROTOCOL("INVALID_FIREWALL_PROTOCOL"),
    INVALID_FIREWALL_DIRECTION("INVALID_FIREWALL_DIRECTION"),
    INVALID_FIREWALL_ACTION("INVALID_FIREWALL_ACTION"),
    INVALID_FIREWALL_CONN_STATE("INVALID_FIREWALL_CONN_STATE"),
    INVALID_SUBNET_TYPE("INVALID_SUBNET_TYPE"),
    INVALID_USER_NAME_FORMAT("INVALID_USER_NAME_FORMAT"),
    INVALID_PASSWORD_FORMAT("INVALID_PASSWORD_FORMAT"),
    INVALID_CHECKSUM_FORMAT("INVALID_CHECKSUM_FORMAT"),
    NO_JOB_FOUND("NO_JOB_FOUND"),
    INVALID_IP_ADDRESS("INVALID_IP_ADDRESS"),
    INVALID_NETMASK("INVALID_NETMASK"),
    INVALID_IP_TYPE("INVALID_IP_TYPE"),
    SNAPSHOT_CANNOT_BE_NULL("SNAPSHOT_CANNOT_BE_NULL"),
    NO_SNAPSHOT_TYPE_DEFINED("NO_SNAPSHOT_TYPE_DEFINED"),
    NO_SNAPSHOT_PARENT_UUID_DEFINED("NO_SNAPSHOT_PARENT_UUID_DEFINED"),
    NO_SNAPSHOT_NAME_DEFINED("NO_SNAPSHOT_NAME_DEFINED"),
    INVALID_NETWORK_UUID("INVALID_NETWORK_UUID"),
    INVALID_SUBNET_UUID("INVALID_SUBNET_UUID"),
    NO_BASE_UUID_SET("NO_BASE_UUID_SET"),
    CAPABILITIES_SET_CANNOT_BE_NULL("CAPABILITIES_SET_CANNOT_BE_NULL"),
    INVALID_FILTER_FIELD("INVALID_FILTER_FIELD"),
    INVALID_SERVER_STATE("INVALID_SERVER_STATE"),
    INVALID_CAPABILITY("INVALID_CAPABILITY"),
    INVALID_RESOURCE_TYPE("INVALID_RESOURCE_TYPE"),
    ENUM_CANNOT_BE_NULL("ENUM_CANNOT_BE_NULL"),
    ENUM_DO_NOT_IMPLEMENT_DBENUM("ENUM_DO_NOT_IMPLEMENT_DBENUM"),
    NO_VDC_UUID_DEFINED("NO_VDC_UUID_DEFINED"),
    NO_CLUSTER_DEFINED("NO_CLUSTER_DEFINED"),
    NO_CLUSTER_NAME_DEFINED("NO_CLUSTER_NAME_DEFINED"),
    RESOURCE_IS_NOT_VIRTUAL_RESOURCE("RESOURCE_IS_NOT_VIRTUAL_RESOURCE"),
    INVALID_CLUSTER_UUID("INVALID_CLUSTER_UUID"),
    INVALID_INPUT("INVALID_INPUT"),
    INVALID_USER_UUID("INVALID_USER_UUID"),
    GROUP_CANNOT_BE_NULL("GROUP_CANNOT_BE_NULL"),
    NO_PAYMENT_CARD_DEFINED("NO_PAYMENT_CARD_DEFINED"),
    INVALID_PAYMENT_METHOD_ID("INVALID_PAYMENT_METHOD_ID"),
    CLUSTER_CANNOT_BE_NULL("CLUSTER_CANNOT_BE_NULL"),
    STORAGE_UNIT_CANNOT_BE_NULL("STORAGE_UNIT_CANNOT_BE_NULL"),
    NO_PRODUCT_DEFINED("NO_PRODUCT_DEFINED"),
    PRODUCT_ID_FOR_DIFFERENT_PRODUCT("PRODUCT_ID_FOR_DIFFERENT_PRODUCT"),
    NO_PAYMENT_METHOD_DEFINED("NO_PAYMENT_METHOD_DEFINED"),
    NO_PAYMENT_PROVIDER_DEFINED("NO_PAYMENT_PROVIDER_DEFINED"),
    NO_PAYMENT_METHOD_NAME_DEFINED("NO_PAYMENT_METHOD_NAME_DEFINED"),
    NO_PAYMENT_METHOD_UUID_DEFINED("NO_PAYMENT_METHOD_UUID_DEFINED"),
    INVALID_PAYMENT_METHOD_UUID("INVALID_PAYMENT_METHOD_UUID"),
    INVALID_PRODUCT_COMPONENTS("INVALID_PRODUCT_COMPONENTS"),
    NO_INVOICE_DEFINED("NO_INVOICE_DEFINED"),
    INVALID_INVOICE_NUMBER("INVALID_INVOICE_NUMBER"),
    INVALID_INVOICE_SOURCE("INVALID_INVOICE_SOURCE"),
    INVALID_INVOICE_PAYMENT_PROVIDER("INVALID_INVOICE_PAYMENT_PROVIDER"),
    INVALID_INVOICE_PAYMENT_PROVIDER_REFERENCE("INVALID_INVOICE_PAYMENT_PROVIDER_REFERENCE"),
    NO_PURCHASE_REFERENCE_DEFINED("NO_PURCHASE_REFERENCE_DEFINED"),
    NO_INVOICE_UUID_DEFINED("NO_INVOICE_UUID_DEFINED"),
    NO_TRANSACTION_LOG_DEFINED("NO_TRANSACTION_LOG_DEFINED"),
    NO_SERVER_SPECIFIED("NO_SERVER_SPECIFIED"),
    NO_AGGREGATION_FUNCTION_DEFINED("NO_AGGREGATION_FUNCTION_DEFINED"),
    NO_AGGREGATION_FIELD_DEFINED("NO_AGGREGATION_FIELD_DEFINED"),
    INVALID_ORDER_BY_FIELD("INVALID_ORDER_BY_FIELD"),
    INVALID_INVOICE_DATE("INVALID_INVOICE_DATE"),
    NO_OUTPUT_FIELDS_DEFINED("NO_OUTPUT_FIELDS_DEFINED"),
    NO_START_OR_END_DATE_DEFINED("NO_START_OR_END_DATE_DEFINED"),
    INVALID_AGGREGATION_CONDITION_IN_FILTER("INVALID_AGGREGATION_CONDITION_IN_FILTER"),
    NO_DEPLOYMENT_TEMPLATE_DEFINED("NO_DEPLOYMENT_TEMPLATE_DEFINED"),
    NO_DEPLOYMENT_TEMPLATE_UUID_DEFINED("NO_DEPLOYMENT_TEMPLATE_UUID_DEFINED"),
    INVALID_DEPLOYMENT_INSTANCE_UUID("INVALID_DEPLOYMENT_INSTANCE_UUID"),
    NO_DEPLOYMENT_INSTANCE_DEFINED("NO_DEPLOYMENT_INSTANCE_DEFINED"),
    NO_NETWORK_DEFINED("NO_NETWORK_DEFINED"),
    NO_CURRENCY_DEFINED("NO_CURRENCY_DEFINED"),
    NO_CURRENCY_CODE_DEFINED("NO_CURRENCY_CODE_DEFINED"),
    CURRENCY_CODE_LENGTH_CANNOT_BE_GREATER_THAN_3("CURRENCY_CODE_LENGTH_CANNOT_BE_GREATER_THAN_3"),
    EXISTING_CURRENCY_CODE("EXISTING_CURRENCY_CODE"),
    INVALID_NAMESPACE("INVALID_NAMESPACE"),
    NO_SUPPORT_FOR_MULTI_VALUES("NO_SUPPORT_FOR_MULTI_VALUES"),
    INVALID_VALUE_SET_FOR_FIELD("INVALID_VALUE_SET_FOR_FIELD"),
    INVALID_VALUE_INPUT("INVALID_VALUE_INPUT"),
    FDL_COMPILE_ERROR("FDL_COMPILE_ERROR"),
    FDL_REGISTER_ERROR("FDL_REGISTER_ERROR"),
    NO_SIZE_SPECIFIED("NO_SIZE_SPECIFIED"),
    INVALID_URL("INVALID_URL"),
    INVALID_PCT("INVALID_PCT"),
    PCT_NOT_DEFINED("PCT_NOT_DEFINED"),
    INVALID_BILLING_METHOD("INVALID_BILLING_METHOD"),
    FDL_CODE_SIGNING_ERROR("FDL_CODE_SIGNING_ERROR"),
    NO_PRODUCT_COMPONENT_SPECIFIED("NO_PRODUCT_COMPONENT_SPECIFIED"),
    REQUIRED_PRODUCT_COMPONENTS_NOT_SET("REQUIRED_PRODUCT_COMPONENTS_NOT_SET");
    private final String value;

    ErrorInvalidInput(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ErrorInvalidInput fromValue(String v) {
        for (ErrorInvalidInput c: ErrorInvalidInput.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
