
package net.flexiant.extility;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserAPI", targetNamespace = "http://extility.flexiant.net", wsdlLocation = "file:/C:/Users/huis/github/dcloudml/deployer/src/main/resources/UserAdmin.wsdl")
public class UserAPI
    extends Service
{

    private final static URL USERAPI_WSDL_LOCATION;
    private final static WebServiceException USERAPI_EXCEPTION;
    private final static QName USERAPI_QNAME = new QName("http://extility.flexiant.net", "UserAPI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/huis/github/dcloudml/deployer/src/main/resources/UserAdmin.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERAPI_WSDL_LOCATION = url;
        USERAPI_EXCEPTION = e;
    }

    public UserAPI() {
        super(__getWsdlLocation(), USERAPI_QNAME);
    }

    public UserAPI(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERAPI_QNAME, features);
    }

    public UserAPI(URL wsdlLocation) {
        super(wsdlLocation, USERAPI_QNAME);
    }

    public UserAPI(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERAPI_QNAME, features);
    }

    public UserAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserAPI(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserService
     */
    @WebEndpoint(name = "UserServicePort")
    public UserService getUserServicePort() {
        return super.getPort(new QName("http://extility.flexiant.net", "UserServicePort"), UserService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserService
     */
    @WebEndpoint(name = "UserServicePort")
    public UserService getUserServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://extility.flexiant.net", "UserServicePort"), UserService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERAPI_EXCEPTION!= null) {
            throw USERAPI_EXCEPTION;
        }
        return USERAPI_WSDL_LOCATION;
    }

}
